---
title: "Subgroup analysis"
author: "Гладышев Никита Сергеевич"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
library(dplyr)
library(broom)
library(ggplot2)
library(stringr)
library(forestplot)
library(grid)
library(tidyr)
```

### Loading and preparing data for analysis

```{r}
analysis_data <- readRDS("C:/Users/krine/Downloads/Telegram Desktop/joint_sepsis.rds") %>%
  filter(shock_T0 == TRUE) %>%
  mutate(unique_patient_id = paste(study_id, study_patient_id, sep = "_"),
         treatment = combined_efferon)

analysis_data <- analysis_data %>%
  mutate(time_point = as.character(time_point))

data_T0 <- analysis_data %>% filter(time_point == "0") %>% select(-time_point)
data_T3 <- analysis_data %>% filter(time_point == "3") %>% select(-time_point)

data_T3 <- data_T3 %>% 
  mutate (SOFA_T3 = SOFA) %>% 
  select (unique_patient_id, SOFA_T3)

analysis_data <- data_T0 %>%
  left_join(data_T3, by = "unique_patient_id") %>%
  mutate(across(starts_with("infection_"), ~ as.numeric(as.character(.))))

analysis_data <- analysis_data %>%
  mutate(
    sex = as.factor(sex),
    treatment = as.factor(treatment),
    SI_CISCIO = as.numeric(SI_CISCIO)) %>% 
  mutate(across(contains("infection"), ~ as.factor(ifelse(. > 0, "Yes", "No"))))
```

### Linear model for all variables

```{r}
analysis_data_scaled <- analysis_data %>%
  mutate(across(where(is.numeric), scale))


base_covariates <- c("SOFA", "NLR", "age", "SI_CISCIO", "sex")
vars <- c("weight", "height", "BMI", "APACHE2", "MAP", "PF_ratio", "lactate", "VIS2020", "WBC", "NEU", "LYM", "PLT", "SII", "aPTT", "fibrinogen", "creatinine", "bilirubin_total", "CRP", "PCT", "IL_6", "infection_g_negative", "infection_g_positive", "infection_virus", "infection_fungi", "hospt_quality_level", "source_cat","SI_CISCIO")


run_lm_sofa <- function(var, data) {
  formula <- as.formula(paste("SOFA_T3 ~", paste(base_covariates, collapse = " + "), 
                              "+ treatment *", var))
  fit <- lm(formula, data = data)
  return(tidy(fit))
}

lm_results <- lapply(vars, function(v) run_lm_sofa(v, analysis_data_scaled))

lm_results_df <- bind_rows(setNames(lm_results, vars), .id = "model_var")


```

### Correction for multiple comparisons and selection of interaction variables

```{r}
lm_results_df <- lm_results_df %>%
  filter(grepl(":", term)) %>%
  mutate(p.adj = p.adjust(p.value, method = "BH"))

significant_vars_sofa <- lm_results_df %>%
#  filter(p.adj < 0.05) %>%
  arrange(p.adj)

```

### Preprocessing for forestplot

```{r}
cat_vars <- c("source_cat", "infection_g_negative", "infection_g_positive", 
                    "infection_virus", "infection_fungi", "hospt_quality_level")

df_cat <- significant_vars_sofa %>%
  filter(str_detect(term, str_c(cat_vars, collapse = "|"))) %>%
  mutate(
    conf.low = estimate - 1.96 * std.error,
    conf.high = estimate + 1.96 * std.error,
    significance = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.01 ~ "**",
      p.value < 0.05 ~ "*",
      TRUE ~ ""
    )
  ) %>%
  arrange(desc(estimate)) %>%
  mutate(term = as.character(term)) %>%
  drop_na()

label_text_cat <- cbind(
  Variable = df_cat$term,
  Estimate = sprintf("%.2f", df_cat$estimate),
  CI = sprintf("[%.2f, %.2f]", df_cat$conf.low, df_cat$conf.high),
  Significance = df_cat$significance
)

df_num <- significant_vars_sofa %>%
  filter(!str_detect(term, str_c(cat_vars, collapse = "|"))) %>%
  mutate(
    conf.low = estimate - 1.96 * std.error,
    conf.high = estimate + 1.96 * std.error,
    significance = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.01 ~ "**",
      p.value < 0.05 ~ "*",
      TRUE ~ ""
    )
  ) %>%
  arrange(desc(estimate)) %>%
  mutate(term = as.character(term)) %>%
  drop_na()

label_text_num <- cbind(
  Variable = df_num$term,
  Estimate = sprintf("%.2f", df_num$estimate),
  CI = sprintf("[%.2f, %.2f]", df_num$conf.low, df_num$conf.high),
  Significance = df_num$significance
)

```


### Forestplots

```{r, fig.height=6}

forestplot(
  labeltext = label_text_cat,
  mean = df_cat$estimate,
  lower = df_cat$conf.low,
  upper = df_cat$conf.high,
  is.summary = FALSE,
  xlab = "Regression Coefficient (95% CI)",
  zero = 0, boxsize = 0.3,
  col = fpColors(box = "blue", line = "darkblue", zero = "red"),
  title = "Forest plot (Categorical Variables)",
  txt_gp = fpTxtGp(xlab = gpar(fontsize = 20), ticks = gpar(fontsize = 20))
)

forestplot(
  labeltext = label_text_num,
  mean = df_num$estimate,
  lower = df_num$conf.low,
  upper = df_num$conf.high,
  is.summary = FALSE,
  xlab = "Regression Coefficient (95% CI)",
  zero = 0, boxsize = 0.3,
  col = fpColors(box = "blue", line = "darkblue", zero = "red"),
  title = "Forest plot (Scaled Numerical Variables)",
  txt_gp = fpTxtGp(xlab = gpar(fontsize = 20), ticks = gpar(fontsize = 20))
)
```



