---
title: "Survival analysis"
author: "Гладышев Никита Сергеевич"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flextable)

library(survival)
library(survminer)

```


# 3. Анализ выживаемости

## 3.1 Предобработка

```{r}
# Формируем уникальные ID

sepsis_clear <- sepsis_clear %>%
  mutate(unique_patient_id = paste(study_id, study_patient_id, sep = "_"))

#Делаем переменные для АВ

sepsis_clear <- sepsis_clear %>%
  mutate(
    event_status = ifelse(shock_first_end_status == "death", 1, 0),
    event_time = shock_dur_T0_first_end
  )

# Группируем пациента по времени наступления исхода

 sepsis_single <- sepsis_clear %>%
  group_by(unique_patient_id) %>%
  summarise(
     treatment = first(treatment),
     event_status = max(event_status),
    event_time = max(event_time, na.rm = TRUE)) 

```

## 3.2 Анализ выживаемости

```{r}
# Анализ выживаемости методом Каплана-Майера

surv_object <- Surv(time = sepsis_single$event_time, event = sepsis_single$event_status)

km_fit <- survfit(surv_object ~ treatment, data = sepsis_single)
```

## 3.3 Визуализация

```{r, fig.width= 7, fig.height=7}

ggsurvplot(km_fit,
           data = sepsis_single,
           pval = TRUE,
           conf.int = TRUE,
           risk.table = TRUE,
           ggtheme = theme_minimal(),
           legend.title = "Группа лечения",
           legend.labs = c("Базовая терапия", "Гемосорбция"))

```

#3.4 Модель пропорциональных рисков Кокса

```{r}
cox_model <- coxph(Surv(event_time, event_status) ~ treatment + IL_6 + VIS2020 + LYM + PF_ratio + SOFA, data = sepsis_clear)

summary(cox_model)
```
##3.5 Визуализация




