---
title: "Sepsis"
author: "Гладышев Никита Сергеевич"
date: "2024-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library (tidyverse)
library(flextable)
library(officer)
library(DescTools)

```


```{r}
sepsis <- read_rds("sepsis_HA_df_v1.rds") %>% glimpse ()
```
# Чистка датасета

```{r}
sepsis_clear <- sepsis %>%
  select(where(~ mean(is.na(.)) <= 0.7)) %>%
  mutate (across (where (is.character), as.factor), 
          across(where(is.logical), as.factor)) %>%
  ungroup ()
```

# Посчитаем описательные статистики

## Количественные переменные

```{r}

ft_num <- sepsis_clear %>%
  select(-study_id, -study_patient_id) %>%
  select(where(is.numeric)) %>%
  summarise(across(everything(), list(
    "Количество значений" = ~ as.character(sum(!is.na(.))),
    "Количество пропущенных значений" = ~ as.character(sum(is.na(.))),
    "Среднее" = ~ as.character(round(mean(., na.rm = TRUE), 2)),
    "Медиана" = ~ as.character(round(median(., na.rm = TRUE), 2)),
    "Стандартное отклонение" = ~ as.character(round(sd(., na.rm = TRUE), 2)),
    "25% квантиль" = ~ as.character(round(quantile(., 0.25, na.rm = TRUE), 2)),
    "75% квантиль" = ~ as.character(round(quantile(., 0.75, na.rm = TRUE), 2)),
    "Межквартильный размах" = ~ as.character(round(IQR(., na.rm = TRUE), 2)),
    "Минимум" = ~ as.character(ifelse(all(is.na(.)), NA, round(min(., na.rm = TRUE), 2))),
    "Максимум" = ~ as.character(ifelse(all(is.na(.)), NA, round(max(., na.rm = TRUE), 2))),
    "95% ДИ для среднего" = ~ paste0(
      round(mean(., na.rm = TRUE) - 1.96 * sd(., na.rm = TRUE) / sqrt(sum(!is.na(.))), 2),
      " - ",
      round(mean(., na.rm = TRUE) + 1.96 * sd(., na.rm = TRUE) / sqrt(sum(!is.na(.))), 2)
    )
  ), .names = "{.col}::{.fn}")) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Value") %>%
  separate(Variable, into = c("Variable", "Statistic"), sep = "::") %>%
  pivot_wider(names_from = Variable, values_from = Value)


summary_stats_table <- flextable(summary_stats_num)

summary_stats_table <- summary_stats_table %>%
  border_remove() %>%
  border_outer(part = "all", border = officer::fp_border(color = "black", width = 1)) %>%
  border_inner_h(border = officer::fp_border(color = "black", width = 1)) %>%
  border_inner_v(border = officer::fp_border(color = "black", width = 1))

summary_stats_table


```

## Качественные данные

```{r}



summary_stats_cat <- sepsis_clear %>%
  select(-study_id, -study_patient_id) %>%
  select(where(~ !is.numeric(.))) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Category") %>%
  filter(!is.na(Category)) %>%
  group_by(Variable, Category) %>%
  summarise(
    Count = n(),
    .groups = 'drop_last'
  ) %>%
  mutate(
    Total = sum(Count),
    Proportion = Count / Total
  ) %>%
  rowwise() %>%
  mutate(
    CI = list(BinomCI(Count, Total, conf.level = 0.95, method = "wilson"))
  ) %>%
  ungroup() %>%
  mutate(
    `95% ДИ Нижняя граница` = map_dbl(CI, ~ .x[1, "lwr.ci"]),
    `95% ДИ Верхняя граница` = map_dbl(CI, ~ .x[1, "upr.ci"])
  ) %>%
  select(-CI)


summary_stats_cat_table <- summary_stats_cat %>%
  select(Variable, Category, Count, Total, Proportion, `95% ДИ Нижняя граница`, `95% ДИ Верхняя граница`)

summary_stats_cat_table <- flextable(summary_stats_cat_table) %>% 
  border_remove() %>%
  border_outer(part = "all", border = officer::fp_border(color = "black", width = 1)) %>%
  border_inner_h(border = officer::fp_border(color = "black", width = 1)) %>%
  border_inner_v(border = officer::fp_border(color = "black", width = 1)) %>% merge_v(j = "Variable")

summary_stats_cat_table

```

