---
title: "Survival analysis"
author: "Гладышев Никита Сергеевич"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library (dplyr)
library(tidycmprsk)
library(ggplot2)
library(ggsurvfit)

```


# 3. Анализ выживаемости

## 3.1 Предобработка

```{r}
# Формируем уникальные ID, делаем переменные "смерть, выздоровление и цензурирование"

sepsis_clear <- readRDS("../../../../sepsis_clear_GNS.rds") %>%
  filter(shock_T0 == TRUE) %>% 
  mutate(
    unique_patient_id = paste(study_id, study_patient_id, sep = "_"),
    event_status = case_when(
      shock_first_end_status == "death" ~ "death",
      shock_first_end_status == "recovery" ~ "recovery",
      is.na(shock_first_end_status) ~ "censored"
    ),
    event_time = shock_dur_T0_first_end
  ) %>%
  mutate(event_status = factor(event_status, levels = c("censored", "recovery", "death")),
         across(where(is.character), as.factor))
# Делаем датафрейм с 
sepsis_single <- sepsis_clear %>%
  filter (event_time < 40) %>% 
  group_by(unique_patient_id) %>%
  summarise(
    treatment = first(treatment),
    event_status = first(event_status),
    event_time = if_else(all(is.na(event_time)), NA_real_, max(event_time, na.rm = TRUE))
  ) %>%
  ungroup()


```

## 3.2 Анализ выживаемости и визуализация исхода: смерть

```{r}

cuminc(Surv(event_time, event_status) ~ treatment, data = sepsis_single) %>%
  ggcuminc(outcome = "death") +
  labs (title = "Кумулятивный риск смерти",
        y = "Кумулятивная вероятность",
        x = "Время",
        color = "Группа лечения") + 
  add_confidence_interval() +
  add_risktable() +
  theme_bw ()

```

## 3.3 Анализ выживаемости и визуализация исхода: выздоровление


```{r}
cuminc(Surv(event_time, event_status) ~ treatment, data = sepsis_single) %>%
  ggcuminc(outcome = "recovery") +
  labs(
    title = "Кумулятивный риск выздоровления",
    x = "Время",
    y = "Кумулятивная вероятность",
    color = "Группа лечения"
  ) + 
  add_confidence_interval() +
  add_risktable() +
  theme_bw ()
```
# Создание df длЯ регрессии Файна-Грея

```{r}
sepsis_single <- sepsis_single %>%
  left_join(
    sepsis_clear %>%
      select(unique_patient_id, age, SOFA, PF_ratio, sex, VIS2020),
    by = "unique_patient_id"
  )
```

# Регрессионный анализ

```{r}

sepsis_single <- sepsis_single %>%
  mutate(event_status = factor(event_status, levels = c("censored", "death", "recovery")))

fine_gray_death <- crr(Surv(event_time, event_status) ~ treatment + age + SOFA + PF_ratio + sex + VIS2020,
  data = sepsis_single
)

fine_gray_results <- fine_gray_death %>%
  broom::tidy() %>%
  mutate(HR = exp(estimate),
         lower_CI = exp(estimate - 1.96 * std.error),
         upper_CI = exp(estimate + 1.96 * std.error))

ggplot(fine_gray_results, aes(x = term, y = HR, ymin = lower_CI, ymax = upper_CI)) +
  geom_pointrange() +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  coord_flip() +
  labs(
    title = "Hazard Ratio для событий",
    x = "Ковариаты",
    y = "Hazard Ratio (HR)"
  ) +
  theme_bw()
```


